var STATE="AL AK AR AS AZ CO CT DC DE FL GA GU HI IA ID IL IN KS KY LA MA MD ME MI MN MO MS MT NC ND NE NH NJ NM NV NY OH OK OR PA PR RI SC SD TN TX UT VA VT WA WI WV WY".split(" "),numStudents=1,numParents=2,cutoffTimestamp=(new Date(2009,12,7)).getTime(),adultTimestamp=(new Date(1996,10,12)).getTime(),submission="",numAdultStudents=0;
$(function(){initDialogs();for(var a=0;a<STATE.length;++a)$("#state").append("<option value="+STATE[a]+">"+STATE[a]+"</option>");for(a=1;4>=a;++a)$("#s"+a+"bd").datepicker({changeMonth:!0,changeYear:!0,dateFormat:"mm-dd-yy",maxDate:new Date,yearRange:"-80:+0"});setNavigationHooks();$("#only1p").change(function(){numParents=this.checked?1:2;clearFamilyErrors();showParents()});$("#num_stu").change(function(){numStudents=$("#num_stu option:selected").val();clearStudentErrors();showStudents()});$("#consent").change(function(){toggleLegalStep()});
for(a=0;7>a;++a)$("#page"+a).hide();localizeButtons();showParents();showStudents();toggleLegalStep();showPage(0)});function initDialogs(){$("#progress").dialog({autoOpen:!1,resizable:!1,modal:!0});$("#error").dialog({autoOpen:!1,resizable:!1,modal:!0,buttons:{OK:function(){$(this).dialog("close")}}})}
function setNavigationHooks(){$("#next0").click(function(){showPage(1)});$("#next1").click(function(){showParents();showPage(2)});$("#next2").click(function(){validateFamilyData()&&(showStudents(),showPage(3))});$("#next3").click(function(){validateStudentData()&&(genSummary(),showPage(4))});$("#next4").click(function(){showPage(5)});$("#next5").click(function(){genFinalData()});$("#prev3").click(function(){showParents();showPage(2)});$("#prev4").click(function(){showStudents();showPage(3)})}
function showPage(a){for(var b=0;7>b;++b){var c="#page"+b;b!=a?$(c).hide():$(c).show()}}function localizeButtons(){if("en"!=lang){for(var a=0;5>a;++a)$("#next"+a).prop("value","\u4e0b\u4e00\u6b65 >>");$("#prev3").prop("value","<< \u4e0a\u4e00\u6b65");$("#prev4").prop("value","<< \u4e0a\u4e00\u6b65");$("#next5").prop("value","tc"==lang?"\u63d0\u4ea4\u7533\u8acb\u8868":"\u63d0\u4ea4\u7533\u8bf7\u8868")}}
function showStudents(){for(var a=1;4>=a;++a){var b="#stu"+a,c="#gs"+a;a<=numStudents?($(b).show(),$(c).show()):($(b).hide(),$(c).hide())}}function showParents(){for(var a="#p2t #p2eng_name #p2chn_name #p2spec #p2work_ph #p2cell_ph #p2email #p2chnlv #p2svcpref".split(" "),b=0;b<a.length;++b)1==numParents?$(a[b]).hide():$(a[b]).show()}function toggleLegalStep(){$("#consent").is(":checked")?$("#next5").removeAttr("disabled"):$("#next5").attr("disabled","disabled")}
function validatePhone(a){a=a.toString().replace(/[^\d+!x]/g,"").split("x");if(2>=a.length&&10==a[0].length){var b=a[0].substr(0,3)+"-"+a[0].substr(3,3)+"-"+a[0].substr(6,4);2==a.length&&a[1].length&&(b+="x"+a[1]);return b}return""}function validateEmail(a){return/^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/i.test(a)?a.toLowerCase():""}
function validateZip(a){return/^([0-9]{5})(?:[-\s]*([0-9]{4}))?$/.test(a)?a.toString():""}function validateChinese(a){return/^[\u4E00-\u9FA5]+$/.test(a)?a.toString():""}function clearFamilyErrors(){$("#parentTable td").removeClass();$("#familyTable td").removeClass()}
function validateFamilyData(){clearFamilyErrors();for(var a=!0,b=1;b<=numParents;++b){$("#p"+b+"eng_name").val().trim().length||(a&=0,$("#pteng_name").addClass("error"));var c=validatePhone($("#p"+b+"cell_ph").val().trim());12!=c.length?(a&=0,$("#ptcell").addClass("error")):$("#p"+b+"cell_ph").val(c);c=$("#p"+b+"work_ph").val().trim();validatePhone(c)!=c&&(a&=0,$("#ptworkph").addClass("error"));c=$("#p"+b+"chn_name").val().trim();validateChinese(c)!=c&&(a&=0,$("#ptchn_name").addClass("error"));c=
validateEmail($("#p"+b+"email").val().trim());4>c.length?(a&=0,$("#ptemail").addClass("error")):$("#p"+b+"email").val(c);var c="#p"+b+"clv1",d="#p"+b+"clv2";$("#p"+b+"clv0").is(":checked")||$(c).is(":checked")||$(d).is(":checked")||(a&=0,$("#ptchnlv").addClass("error"))}$("#addr").val().trim().length||(a&=0,$("#ptaddr").addClass("error"));$("#city").val().trim().length||(a&=0,$("#ptcity").addClass("error"));5!=validateZip($("#zip").val().trim()).length&&(a&=0,$("#ptzip").addClass("error"));b=validatePhone($("#home_ph").val().trim());
12!=b.length?(a&=0,$("#pthome_ph").addClass("error")):$("#home_ph").val(b);b=validatePhone($("#doc_ph").val().trim());0!=b.length&&12!=b.length?(a&=0,$("#ptdoc_ph").addClass("error")):$("#doc_ph").val(b);b=validatePhone($("#emer_ph").val().trim());0!=b.length&&12!=b.length?(a&=0,$("#ptemer_ph").addClass("error")):$("#emer_ph").val(b);return a}function clearStudentErrors(){for(var a=1;4>=a;++a)$("#stu"+a+" td").removeClass()}
function validateStudentData(){clearStudentErrors();var a=!0;numAdultStudents=0;for(var b=1;b<=numStudents;++b){$("#s"+b+"ln").val().trim().length||(a&=0,$("#s"+b+"tln").addClass("error"));$("#s"+b+"fn").val().trim().length||(a&=0,$("#s"+b+"tfn").addClass("error"));var c=$("#s"+b+"chn").val().trim();validateChinese(c)!=c&&(a&=0,$("#s"+b+"tcn").addClass("error"));var c=$("#s"+b+"bd").val().toString(),d=!1;if(c.length){var e=0;try{e=jQuery.datepicker.parseDate("mm-dd-yy",c).getTime()}catch(f){}e<cutoffTimestamp&&
(d=!0);e<adultTimestamp&&numAdultStudents++}d||(a&=0,$("#s"+b+"tbd").addClass("error"));c="#s"+b+"gf";$("#s"+b+"gm").is(":checked")||$(c).is(":checked")||(a&=0,$("#s"+b+"tg").addClass("error"));c="#s"+b+"sn";$("#s"+b+"sy").is(":checked")||$(c).is(":checked")||(a&=0,$("#s"+b+"ts").addClass("error"))}return a}
function genFamilySummary(){var a={address:$("#addr").val().toString(),city:$("#city").val().toString(),state:$("#state").val().toString(),zip:$("#zip").val().toString(),home_ph:$("#home_ph").val().toString(),doc_name:$("#doc_name").val().toString(),doc_ph:$("#doc_ph").val().toString(),emer_name:$("#emer_name").val().toString(),emer_ph:$("#emer_ph").val().toString(),video_consent:!0};$("#gaddr").text(a.address);$("#gcity").text(a.city);$("#gstate").text(a.state);$("#gzip").text(a.zip);$("#ghome_ph").text(a.home_ph);
$("#gdoc_name").text(a.doc_name);$("#gdoc_ph").text(a.doc_ph);$("#gemer_name").text(a.emer_name);$("#gemer_ph").text(a.emer_ph);return a}function getChineseLevelString(a){return 0==a?"Non-speaker":1==a?"Listen/Speak Only":"Native Educated"}
function genParentSummary(){for(var a=[],b=1;b<=numParents;++b){var c={eng_name:$("#p"+b+"eng_name").val().toString(),chn_name:$("#p"+b+"chn_name").val().toString(),spec:$("#p"+b+"spec").val().toString(),work_ph:$("#p"+b+"work_ph").val().toString(),cell_ph:$("#p"+b+"cell_ph").val().toString(),email:$("#p"+b+"email").val().toString(),chnlv:$("#p"+b+"clv0").is(":checked")?0:$("#p"+b+"clv1").is(":checked")?1:2};a.push(c);$("#gp"+b+"eng_name").text(c.eng_name);$("#gp"+b+"chn_name").text(c.chn_name);$("#gp"+
b+"spec").text(c.spec);$("#gp"+b+"work_ph").text(c.work_ph);$("#gp"+b+"cell_ph").text(c.cell_ph);$("#gp"+b+"email").text(c.email);$("#gp"+b+"chnlv").text(getChineseLevelString(c.chnlv))}return a}function localizeGender(a){return"en"==lang?a:"M"==a?"\u7537":"\u5973"}function getPrefString(a){return 1==a?"1. Traditional Zhuyin \u7e41\u9ad4\u6ce8\u97f3":2==a?"2. Traditional Pinyin \u7e41\u9ad4\u62fc\u97f3":"3. Simplified \u7b80\u4f53"}
function getLearnedString(a){switch(parseInt(a,10)){case 1:return"<1 year";case 2:return"1 - 2 years";case 3:return"2+ years";default:return"No"}}
function genStudentSummary(){for(var a=[],b=1;b<=numStudents;++b){var c="#s"+b+"gm",d="#s"+b+"sy",c={last_name:$("#s"+b+"ln").val().toString(),first_name:$("#s"+b+"fn").val().toString(),chn_name:$("#s"+b+"chn").val().toString(),dob:$("#s"+b+"bd").val().toString(),gender:$(c).is(":checked")?"M":"F",sch:$(d).is(":checked")?"Y":"N",pref:$("#s"+b+"pref").val(),tshirt:$("#s"+b+"tshirt").val().toString(),learned:$("#s"+b+"learned").val()};a.push(c);$("#gs"+b+"ln").text(c.last_name);$("#gs"+b+"fn").text(c.first_name);
$("#gs"+b+"chn").text(c.chn_name);$("#gs"+b+"bd").text(c.dob);$("#gs"+b+"gender").text(localizeGender(c.gender));$("#gs"+b+"s").text(c.sch);$("#gs"+b+"pref").text(getPrefString(c.pref));$("#gs"+b+"tshirt").text(c.tshirt);$("#gs"+b+"learned").text(getLearnedString(c.learned))}return a}function genSummary(){var a={family:genFamilySummary(),parents:genParentSummary(),students:genStudentSummary()};submission=JSON.stringify(a)}
function onServerReturn(a){$("#systemdata").html(a);$("#progress").dialog("close");$("#snum_stu").text(numStudents.toString());var b=0<numStudents-numAdultStudents?200:0;$("#ssvc_deposit").text(b.toString());a=700*numStudents+b+100;b=600*numStudents+b+100;$("#stotal").text(a.toString());$("#stotal2").text(b.toString());showPage(6)}function onServerFailure(a){$("#progress").dialog("close");$("#error").dialog("open");$("#next5").removeAttr("disabled");console.log(a)}
function genFinalData(){$("#next5").attr("disabled","disabled");$("#progress").dialog("open");$.ajax({type:"POST",url:"https://script.google.com/macros/s/AKfycbxqx88xp0nKnULwYVyjZT9Y9_7pGwxhsj2YXYCAjjASW6fwpwA5/exec",data:submission,dataType:"text"}).done(function(a){onServerReturn(a)}).fail(function(a){onServerFailure(a)})};
